//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package fi.vm.yti.terminology.api.v2.ntrf;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for languages.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="languages">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="af"/>
 *     <enumeration value="am"/>
 *     <enumeration value="ar"/>
 *     <enumeration value="as"/>
 *     <enumeration value="az"/>
 *     <enumeration value="be"/>
 *     <enumeration value="bg"/>
 *     <enumeration value="bn"/>
 *     <enumeration value="br"/>
 *     <enumeration value="bs"/>
 *     <enumeration value="ca"/>
 *     <enumeration value="cs"/>
 *     <enumeration value="da"/>
 *     <enumeration value="de"/>
 *     <enumeration value="el"/>
 *     <enumeration value="en"/>
 *     <enumeration value="es"/>
 *     <enumeration value="et"/>
 *     <enumeration value="eu"/>
 *     <enumeration value="fa"/>
 *     <enumeration value="fi"/>
 *     <enumeration value="fo"/>
 *     <enumeration value="fr"/>
 *     <enumeration value="gl"/>
 *     <enumeration value="gu"/>
 *     <enumeration value="ha"/>
 *     <enumeration value="he"/>
 *     <enumeration value="hi"/>
 *     <enumeration value="hr"/>
 *     <enumeration value="hu"/>
 *     <enumeration value="hy"/>
 *     <enumeration value="id"/>
 *     <enumeration value="ig"/>
 *     <enumeration value="is"/>
 *     <enumeration value="it"/>
 *     <enumeration value="ja"/>
 *     <enumeration value="ka"/>
 *     <enumeration value="kk"/>
 *     <enumeration value="km"/>
 *     <enumeration value="kn"/>
 *     <enumeration value="ks"/>
 *     <enumeration value="ky"/>
 *     <enumeration value="la"/>
 *     <enumeration value="ln"/>
 *     <enumeration value="lt"/>
 *     <enumeration value="lv"/>
 *     <enumeration value="mk"/>
 *     <enumeration value="ml"/>
 *     <enumeration value="mn"/>
 *     <enumeration value="mr"/>
 *     <enumeration value="ms"/>
 *     <enumeration value="nl"/>
 *     <enumeration value="no"/>
 *     <enumeration value="or"/>
 *     <enumeration value="pa"/>
 *     <enumeration value="pl"/>
 *     <enumeration value="ps"/>
 *     <enumeration value="pt"/>
 *     <enumeration value="pt-br"/>
 *     <enumeration value="pt-pt"/>
 *     <enumeration value="ro"/>
 *     <enumeration value="ru"/>
 *     <enumeration value="si"/>
 *     <enumeration value="sk"/>
 *     <enumeration value="sl"/>
 *     <enumeration value="sq"/>
 *     <enumeration value="sr"/>
 *     <enumeration value="st"/>
 *     <enumeration value="sv"/>
 *     <enumeration value="sw"/>
 *     <enumeration value="ta"/>
 *     <enumeration value="te"/>
 *     <enumeration value="tg"/>
 *     <enumeration value="th"/>
 *     <enumeration value="tk"/>
 *     <enumeration value="tl"/>
 *     <enumeration value="tr"/>
 *     <enumeration value="uk"/>
 *     <enumeration value="ur"/>
 *     <enumeration value="uz"/>
 *     <enumeration value="vi"/>
 *     <enumeration value="xh"/>
 *     <enumeration value="yo"/>
 *     <enumeration value="zc"/>
 *     <enumeration value="zh"/>
 *     <enumeration value="zt"/>
 *     <enumeration value="zu"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "languages")
@XmlEnum
public enum Languages {

    @XmlEnumValue("af")
    AF("af"),
    @XmlEnumValue("am")
    AM("am"),
    @XmlEnumValue("ar")
    AR("ar"),
    @XmlEnumValue("as")
    AS("as"),
    @XmlEnumValue("az")
    AZ("az"),
    @XmlEnumValue("be")
    BE("be"),
    @XmlEnumValue("bg")
    BG("bg"),
    @XmlEnumValue("bn")
    BN("bn"),
    @XmlEnumValue("br")
    BR("br"),
    @XmlEnumValue("bs")
    BS("bs"),
    @XmlEnumValue("ca")
    CA("ca"),
    @XmlEnumValue("cs")
    CS("cs"),
    @XmlEnumValue("da")
    DA("da"),
    @XmlEnumValue("de")
    DE("de"),
    @XmlEnumValue("el")
    EL("el"),
    @XmlEnumValue("en")
    EN("en"),
    @XmlEnumValue("es")
    ES("es"),
    @XmlEnumValue("et")
    ET("et"),
    @XmlEnumValue("eu")
    EU("eu"),
    @XmlEnumValue("fa")
    FA("fa"),
    @XmlEnumValue("fi")
    FI("fi"),
    @XmlEnumValue("fo")
    FO("fo"),
    @XmlEnumValue("fr")
    FR("fr"),
    @XmlEnumValue("gl")
    GL("gl"),
    @XmlEnumValue("gu")
    GU("gu"),
    @XmlEnumValue("ha")
    HA("ha"),
    @XmlEnumValue("he")
    HE("he"),
    @XmlEnumValue("hi")
    HI("hi"),
    @XmlEnumValue("hr")
    HR("hr"),
    @XmlEnumValue("hu")
    HU("hu"),
    @XmlEnumValue("hy")
    HY("hy"),
    @XmlEnumValue("id")
    ID("id"),
    @XmlEnumValue("ig")
    IG("ig"),
    @XmlEnumValue("is")
    IS("is"),
    @XmlEnumValue("it")
    IT("it"),
    @XmlEnumValue("ja")
    JA("ja"),
    @XmlEnumValue("ka")
    KA("ka"),
    @XmlEnumValue("kk")
    KK("kk"),
    @XmlEnumValue("km")
    KM("km"),
    @XmlEnumValue("kn")
    KN("kn"),
    @XmlEnumValue("ks")
    KS("ks"),
    @XmlEnumValue("ky")
    KY("ky"),
    @XmlEnumValue("la")
    LA("la"),
    @XmlEnumValue("ln")
    LN("ln"),
    @XmlEnumValue("lt")
    LT("lt"),
    @XmlEnumValue("lv")
    LV("lv"),
    @XmlEnumValue("mk")
    MK("mk"),
    @XmlEnumValue("ml")
    ML("ml"),
    @XmlEnumValue("mn")
    MN("mn"),
    @XmlEnumValue("mr")
    MR("mr"),
    @XmlEnumValue("ms")
    MS("ms"),
    @XmlEnumValue("nl")
    NL("nl"),
    @XmlEnumValue("no")
    NO("no"),
    @XmlEnumValue("or")
    OR("or"),
    @XmlEnumValue("pa")
    PA("pa"),
    @XmlEnumValue("pl")
    PL("pl"),
    @XmlEnumValue("ps")
    PS("ps"),
    @XmlEnumValue("pt")
    PT("pt"),
    @XmlEnumValue("pt-br")
    PT_BR("pt-br"),
    @XmlEnumValue("pt-pt")
    PT_PT("pt-pt"),
    @XmlEnumValue("ro")
    RO("ro"),
    @XmlEnumValue("ru")
    RU("ru"),
    @XmlEnumValue("si")
    SI("si"),
    @XmlEnumValue("sk")
    SK("sk"),
    @XmlEnumValue("sl")
    SL("sl"),
    @XmlEnumValue("sq")
    SQ("sq"),
    @XmlEnumValue("sr")
    SR("sr"),
    @XmlEnumValue("st")
    ST("st"),
    @XmlEnumValue("sv")
    SV("sv"),
    @XmlEnumValue("sw")
    SW("sw"),
    @XmlEnumValue("ta")
    TA("ta"),
    @XmlEnumValue("te")
    TE("te"),
    @XmlEnumValue("tg")
    TG("tg"),
    @XmlEnumValue("th")
    TH("th"),
    @XmlEnumValue("tk")
    TK("tk"),
    @XmlEnumValue("tl")
    TL("tl"),
    @XmlEnumValue("tr")
    TR("tr"),
    @XmlEnumValue("uk")
    UK("uk"),
    @XmlEnumValue("ur")
    UR("ur"),
    @XmlEnumValue("uz")
    UZ("uz"),
    @XmlEnumValue("vi")
    VI("vi"),
    @XmlEnumValue("xh")
    XH("xh"),
    @XmlEnumValue("yo")
    YO("yo"),
    @XmlEnumValue("zc")
    ZC("zc"),
    @XmlEnumValue("zh")
    ZH("zh"),
    @XmlEnumValue("zt")
    ZT("zt"),
    @XmlEnumValue("zu")
    ZU("zu");
    private final String value;

    Languages(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Languages fromValue(String v) {
        for (Languages c: Languages.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
